### ISSUE TITLE
win7运行报错

### ISSUE THREAD

**Issue by JakeWoki** [easy-team/egg-vue-webpack-boilerplate#107]
2018-12-29 17:32:19,646 INFO 15472 [master] node version v8.11.1
2018-12-29 17:32:19,648 INFO 15472 [master] egg version 2.12.0
2018-12-29 17:32:20,894 WARN 20652 [egg-loader] D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-webpack-vue\agent.js must exports a boot class
2018-12-29 17:32:20,982 INFO 15472 [master] agent_worker#1:20652 started (1328ms)
D:\egg\egg-vue-webpack-boilerplate\node_modules\egg\lib\application.js:69
      throw e;
      ^

Error: [egg-core] load file: D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-view-vue-ssr\app\extend\application.js, error:

Vue packages version mismatch:

- vue@2.5.17
- vue-server-renderer@2.5.21

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (D:\egg\egg-vue-webpack-boilerplate\node_modules\vue-server-renderer\index.js:8:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-view-vue-ssr\lib\engine.js:7:27)
    at Module._compile (module.js:652:30)
[2018-12-29 17:32:21.663] [cfork:master:15472] worker:19596 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
[2018-12-29 17:32:21.664] [cfork:master:15472] don't fork, because worker:19596 will be kill soon
2018-12-29 17:32:21,664 INFO 15472 [master] app_worker#1:19596 disconnect, suicide: false, state: disconnected, current workers: ["1"]
[2018-12-29 17:32:21.668] [cfork:master:15472] worker:19596 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork
: true)
2018-12-29 17:32:21,669 ERROR 15472 nodejs.AppWorkerDiedError: [master] app_worker#1:19596 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-cluster\lib\master.js:398:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-cluster\lib\utils\messenger.js:133:17)
    at Messenger.send (D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-cluster\lib\utils\messenger.js:98:12)
    at EventEmitter.cluster.on (D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-cluster\lib\master.js:267:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:186:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 15472
hostname: USER-201605fhm

2018-12-29 17:32:21,671 ERROR 15472 [master] app_worker#1:19596 start fail, exiting with code:1
2018-12-29 17:32:21,671 ERROR 15472 [master] exit with code:1
⚠️  Error: D:\egg\egg-vue-webpack-boilerplate\node_modules\egg-bin\lib\start-cluster {"baseDir":"D:\\egg\\egg-vue-webpack-boilerplate","workers":1,"framework":"D:\\egg\\
egg-vue-webpack-boilerplate\\node_modules\\egg"} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-vue-webpack-boilerplate@4.4.6 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg-vue-webpack-boilerplate@4.4.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-29T09_32_21_704Z-debug.log

**Comment by HiuYanChong** [comment]
Vue packages version mismatch:
* vue@2.5.17
* vue-server-renderer@2.5.21

This may cause things to work incorrectly. Make sure to use the same version for both.

vue 相关包版本不一致导致的，把依赖删了重装试试吧

**Comment by JakeWoki** [comment]
下周试试

**Comment by JakeWoki** [comment]
为什么我删除了全局的vue版本，package.json里的vue还是2.5.0不变，下载下来却是2.5.17呢？其它项目package.json里设置vue的版本是哪个就是哪个

**Comment by ZQun** [comment]
package-lock.json删了吗

**Comment by JakeWoki** [comment]
@ZQun 删除package-lock.json后可以了，但是为什么一开始不行呢？全局的vue版本不是不影响当前项目设置的版本的吗？

**Comment by ZQun** [comment]
package-lock.json会锁定版本

**Comment by JakeWoki** [comment]
一开始是自动生成的，项目配置的是2.5.0，哪来的锁定2.5.17？

**Comment by ZQun** [comment]
https://www.zhihu.com/question/62331583
