### ISSUE TITLE
server render bundle error

### ISSUE THREAD

**Issue by morphysh** [easy-team/egg-vue-webpack-boilerplate#112]
2019-01-23 10:07:53,010 ERROR 5987 [home/index.js] server render bundle error, try client render, the server render error /Users/omg/codes/boce/front-end-refactor/node_modules/element-ui-verify/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { import rules from './rules';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at r (/Users/omg/codes/boce/front-end-refactor/node_modules/vue-server-renderer/build.js:8360:16)
    at eval (webpack:///external_%22element-ui-verify%22?:1:18)
    at Object.element-ui-verify (__vue_ssr_bundle__:1934:1)
    at __webpack_require__ (__vue_ssr_bundle__:20:30)
    at eval (webpack:///./app/web/component/layout/user/main.vue?./node_modules/babel-loader/lib?%7B%22forceEnv%22:%22node%22,%22cacheDirectory%22:%22/var/folders/29/yhf0dkgx1v3cpzw7gbhb80zc0000gn/T/easywebpack/front-end-refactor/dev/cache/server/babel-loader%22%7D!./node_modules/vue-loader/lib/selector.js?type=script&index=0:9:75)
    at Module../node_modules/babel-loader/lib/index.js?{"forceEnv":"node","cacheDirectory":"/var/folders/29/yhf0dkgx1v3cpzw7gbhb80zc0000gn/T/easywebpack/front-end-refactor/dev/cache/server/babel-loader"}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/web/component/layout/user/main.vue (__vue_ssr_bundle__:970:1)

请问这个问题是需要在webpack中配置什么吗？

**Comment by hubcarl** [comment]
see https://www.yuque.com/easy-team/easywebpack/problem
![image](https://user-images.githubusercontent.com/4983042/52693646-39a78c80-2fa2-11e9-85ed-bf887565ebc6.png)
