### ISSUE TITLE
将node_modules一起打包部署到线上启动提示 Cannot find module

### ISSUE THREAD

**Issue by zhengtulymGh** [easy-team/egg-vue-webpack-boilerplate#130]
通过jenkins部署，将node_modules一并打包后上传到服务器，执行启动命令报错：

打包命令：
`zip -r demo_.zip ./*`

启动报错：
```
> egg-vue-mpa-ssr@1.0.0 start /data/demo/code/demo_b3ca46998d7f832328c7327d9b6c1826/data
> egg-scripts start --port=8080 --daemon


> egg-vue-mpa-ssr@1.0.0 stop /data/demo/code/demo_b3ca46998d7f832328c7327d9b6c1826/data
> egg-scripts stop

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/data/demo/code/demo_b3ca46998d7f832328c7327d9b6c1826/data/node_modules/.bin/egg-scripts:5:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-vue-mpa-ssr@1.0.0 start: `egg-scripts start --port=8080 --daemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-vue-mpa-ssr@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2019-08-24T07_59_20_585Z-debug.log
```

如果打包命令加上参数y：
`zip -ry demo_.zip ./*`

启动报错：
```
> egg-vue-mpa-ssr@1.0.0 start /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data
> egg-scripts start --port=8080 --daemon


> egg-vue-mpa-ssr@1.0.0 stop /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data
> egg-scripts stop

[egg-scripts] stopping egg application 
[egg-scripts] Starting egg application at /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data
[egg-scripts] Run node /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-scripts/lib/start-cluster {"port":8080,"baseDir":"/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data","framework":"/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg","title":"egg-server-egg-vue-mpa-ssr"} --title=egg-server-egg-vue-mpa-ssr
[egg-scripts] Save log file to /home/app/logs
[egg-scripts] can't detect any running egg process
[egg-scripts] stopped
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] tail -n 100 /home/app/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg/lib/application.js:70
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] Error: [egg-core] load file: /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-view-vue-ssr/app/extend/application.js, error: Cannot find module 'vue'
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:637:17)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:20:18)
[egg-scripts]     at Object.<anonymous> (/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-view-vue-ssr/lib/engine.js:5:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[egg-scripts]     at Module.load (internal/modules/cjs/loader.js:599:32)
[egg-scripts]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[egg-scripts] /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg/lib/application.js:70
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] Error: [egg-core] load file: /data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-view-vue-ssr/app/extend/application.js, error: Cannot find module 'vue'
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:637:17)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:20:18)
[egg-scripts]     at Object.<anonymous> (/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-view-vue-ssr/lib/engine.js:5:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[egg-scripts]     at Module.load (internal/modules/cjs/loader.js:599:32)
[egg-scripts]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[egg-scripts] 2019-08-24 17:00:26,545 ERROR 25264 nodejs.AppWorkerDiedError: [master] app_worker#2:25300 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1"]
[egg-scripts]     at Master.onAppExit (/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-cluster/lib/master.js:428:21)
[egg-scripts]     at Master.emit (events.js:182:13)
[egg-scripts]     at Messenger.sendToMaster (/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at EventEmitter.cluster.on (/data/demo/code/demo_5329f239abde60cfe170b6792f9c9950/data/node_modules/egg-cluster/lib/master.js:297:22)
[egg-scripts]     at EventEmitter.emit (events.js:187:15)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:194:13)
[egg-scripts]     at Object.onceWrapper (events.js:273:13)
[egg-scripts]     at ChildProcess.emit (events.js:182:13)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 25264
[egg-scripts] hostname: demo-pre-10-102-44-58.v-bj-3.vivo.lan
[egg-scripts] 
[egg-scripts] 2019-08-24 17:00:26,547 ERROR 25264 [master] app_worker#2:25300 start fail, exiting with code:1
[egg-scripts] 2019-08-24 17:00:26,547 ERROR 25264 [master] exit with code:1
[egg-scripts] 2019-08-24 17:00:26,552 ERROR 25285 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2019-08-24 17:00:26,557 ERROR 25285 [agent_worker] exit with code:110
[egg-scripts] 
[egg-scripts] Start got error, see /home/app/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-vue-mpa-ssr@1.0.0 start: `egg-scripts start --port=8080 --daemon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-vue-mpa-ssr@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2019-08-24T09_00_27_628Z-debug.log
```

**Comment by hubcarl** [comment]
@zhengtulymGh  Cannot find module 'vue' 错误 

- 确保  vue 依赖是安装在  package.json 的  dependencies 节点
- 确保  线上 node_modules 里面有  vue 依赖

**Comment by zhengtulymGh** [comment]
是这样的，这两点都满足
