### ISSUE TITLE
在服务端部署时报 const dllWebpackConfig = builder.getDllWebpackConfig(config, option);

### ISSUE THREAD

**Issue by jankerli** [easy-team/egg-vue-webpack-boilerplate#134]
在服务端运行`npm run build`后显示
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none was installed.
npm WARN babel-loader@8.0.6 requires a peer of @babel/core@^7.0.0 but none was installed.
npm WARN @typescript-eslint/parser@2.6.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none was installed.
npm WARN @typescript-eslint/eslint-plugin@2.6.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none was installed.
npm info ok
[easywebpack-cli]:install [ easywebpack-vue ] success
/data/cc.witbird.com.cn/node_modules/easywebpack-cli/lib/builder.js:90
    const dllWebpackConfig = builder.getDllWebpackConfig(config, option);
                                    ^

TypeError: Cannot read property 'getDllWebpackConfig' of null
    at Object.exports.build (/data/cc.witbird.com.cn/node_modules/easywebpack-cli/lib/builder.js:90:37)
    at Command.program.command.description.action.env (/data/cc.witbird.com.cn/node_modules/easywebpack-cli/bin/cli.js:108:13)
    at Command.listener (/data/cc.witbird.com.cn/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/data/cc.witbird.com.cn/node_modules/commander/index.js:651:12)
    at Command.parse (/data/cc.witbird.com.cn/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/data/cc.witbird.com.cn/node_modules/easywebpack-cli/bin/cli.js:208:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 3.10.0-957.10.1.el7.x86_64
npm ERR! argv "/data/application/node-v6.9.5-linux-x64/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! egg-vue-webpack-mpa-boilerplate@4.1.3 build: `easy build prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg-vue-webpack-mpa-boilerplate@4.1.3 build script 'easy build prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the egg-vue-webpack-mpa-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     easy build prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs egg-vue-webpack-mpa-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls egg-vue-webpack-mpa-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/cc.witbird.com.cn/npm-debug.log
`

请问这是什么原因呀？

**Comment by jankerli** [comment]
已解决，是服务器node、npm版本低的原因。
