### ISSUE TITLE
怎么实现在layout.js中的服务端渲染输出内联 js

### ISSUE THREAD

**Issue by webaifei** [easy-team/egg-vue-webpack-boilerplate#137]
// layout.js中
```
template: EASY_ENV_IS_BROWSER ? tpl : `<!DOCTYPE html>
                  <html lang="zh-CN">
                    <head>
                      <title>{{vTitle}}</title>
                      <meta charset="utf-8">
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="keywords" :content="vKeywords">
                      <meta name="description" :content="vDescription">
                      <meta http-equiv="content-type" content="text/html;charset=utf-8">
                      <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
                      <link rel="apple-touch-icon" href="/logo.png">
                      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
                      ${remjs}
                    </head>
                    <body :class="baseClass">
                      ${tpl}
                    </body>
                  </html>`,
```
想要实现把rem适配方案js直接内联输出 ，目前特殊字符被转义了

**Comment by hubcarl** [comment]
@webaifei https://www.yuque.com/easy-team/easywebpack/wb66pe 看看这个底部的静态资源内联

**Comment by webaifei** [comment]
@hubcarl

**Comment by webaifei** [comment]
@hubcarl 
是这样使用吗
```
`<!DOCTYPE html>
                  <html lang="zh-CN">
                    <head>
                      <title>{{vTitle}}</title>
                      <meta charset="utf-8">
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="keywords" :content="vKeywords">
                      <meta name="description" :content="vDescription">
                      <meta http-equiv="content-type" content="text/html;charset=utf-8">
                      <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
                      <link rel="apple-touch-icon" href="/logo.png">
                      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
                      <template v-html="require('raw-loader!../../../js/rem.js')"></template>
                    </head>
                    <body :class="baseClass">
                      ${tpl}
                    </body>
                  </html>`
```

报错： Error in render: "ReferenceError: require is not defined"
详细报错：
```
2019-12-11 18:50:49,233 ERROR 86477 [index/index.js] server render bundle error, try client render, the server render error ReferenceError: require is not defined
    at Proxy.eval (eval at createFunction (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:6161:12), <anonymous>:2:318)
    at VueComponent.Vue._render (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
    at resolve (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8400:27)
    at waitForServerPrefetch (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at renderNode (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at resolve (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8641:7)
    at waitForServerPrefetch (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at render (/Users/u51/projects/woaika/node/node-service-m/node_modules/vue-server-renderer/build.dev.js:8643:5)
```

**Comment by webaifei** [comment]
![image](https://user-images.githubusercontent.com/7246876/70615975-64a55000-1c48-11ea-81b1-914c8c9330a5.png)

**Comment by hubcarl** [comment]
@webaifei  https://github.com/easy-team/egg-vue-webpack-boilerplate/commit/91190e3ac3ceb8309c14e9f1b67ba395df691524
