### ISSUE TITLE
listen EACCES: permission denied 0.0.0.0:9001

### ISSUE THREAD

**Issue by achuan-web** [easy-team/egg-vue-webpack-boilerplate#146]
克隆了这个项目 yarn && yarn dev 
就这个亚子了
好像是端口无权限还是占用了，但我不知道如何解决
麻烦您帮帮忙
webpack build [=======                                                           ] 10% (0.0 seconds)events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:9001
    at Server.setupListenHandle [as _listen2] (net.js:1281:19)
    at listenInCluster (net.js:1346:12)
    at Server.listen (net.js:1434:7)
    at Application.app.listen (C:\Users\y1\Desktop\egg-vue-webpack-boilerplate-master\node_modules\koa\lib\application.js:74:24)
    at WebpackTool.createWebpackServer (C:\Users\y1\Desktop\egg-vue-webpack-boilerplate-master\node_modules\webpack-tool\lib\tool.js:268:9)
    at process.<anonymous> (C:\Users\y1\Desktop\egg-vue-webpack-boilerplate-master\node_modules\egg-webpack\lib\child-process.js:19:17)
    at process.emit (events.js:209:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1325:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 9001
}

**Comment by achuan-web** [comment]
虽然还是不知道为什么9001会被占用 但我把 webpack启动端口改为了9100+9001解决了这个报错

**Comment by hubcarl** [comment]
@achuan-web easy kill 9001 或者 lsof -i:9001 看看被哪个进程占用了
