### ISSUE TITLE
项目构建报错：PostCSS plugin postcss-discard-comments requires PostCSS 8.

### ISSUE THREAD

**Issue by WinfredWang** [easy-team/egg-vue-webpack-boilerplate#176]
ERROR in css/common.7b13c1c5.css
css/common.7b13c1c5.css from Css Minimizer plugin
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\postcss.js:55:10)
    at cssnanoPlugin (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\cssnano\src\index.js:156:10)
    at cssnanoMinify (eval at transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:79:28), <anonymous>:95:33)
    at minify (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:37:32)      
    at Object.transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:80:10)
    at execFunction (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:148:17)  
    at execHelper (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:127:5)     
    at execMethod (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:131:5)     

ERROR in css/spa.b80d562b.css
css/spa.b80d562b.css from Css Minimizer plugin
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\postcss.js:55:10)
    at cssnanoPlugin (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\cssnano\src\index.js:156:10)
    at cssnanoMinify (eval at transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:79:28), <anonymous>:95:33)
    at minify (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:37:32)      
    at Object.transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:80:10)
    at execFunction (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:148:17)  
    at execHelper (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:127:5)     
    at execMethod (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:131:5)     

ERROR in css/spa.fbb750fd.css
css/spa.fbb750fd.css from Css Minimizer plugin
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\postcss.js:55:10)
    at cssnanoPlugin (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\cssnano\src\index.js:156:10)
    at cssnanoMinify (eval at transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:79:28), <anonymous>:95:33)
    at minify (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:37:32)      
    at Object.transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:80:10)
    at execFunction (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:148:17)  
    at execHelper (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:127:5)     
    at execMethod (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:131:5)     

ERROR in css/common.386cbdf2.css
css/common.386cbdf2.css from Css Minimizer plugin
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\postcss\lib\postcss.js:55:10)
    at cssnanoPlugin (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\cssnano\src\index.js:156:10)
    at cssnanoMinify (eval at transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:79:28), <anonymous>:95:33)
    at minify (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:37:32)      
    at Object.transform (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\css-minimizer-webpack-plugin\dist\minify.js:80:10)
    at execFunction (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:148:17)  
    at execHelper (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:127:5)     
    at execMethod (D:\repo\egg-vue-webpack-boilerplate-master\packages\egg-vue-webpack-spa-boilerplate\node_modules\jest-worker\build\workers\threadChild.js:131:5)

**Comment by nodous** [comment]
同问

**Comment by nodous** [comment]
这个百度能解决，node环境引起的，换一个低版本的14.xxxx
